//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafateriaSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int order_id { get; set; }
        public int menu_id { get; set; }
        public string item_name { get; set; }
        public int item_quantity { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Order Order { get; set; }
    }
}
