//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafateriaSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string bill_number { get; set; }
        public string payer_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<decimal> bill_value { get; set; }
        public string confirmation_number { get; set; }
        public int payment_id { get; set; }
        public string payment_status { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
